# Generated by Django 5.2 on 2026-05-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
