# Generated by Django 5.2 on 2026-05-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_alter_author_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
